"""add Role  permission

Revision ID: 354a6e9d2755
Revises: 712cef586ede
Create Date: 2019-12-20 16:56:08.110532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354a6e9d2755'
down_revision = '712cef586ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
