"""empty message

Revision ID: 455b241372cf
Revises: 20c32527a9b1
Create Date: 2019-12-20 01:27:33.215375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455b241372cf'
down_revision = '20c32527a9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
