"""add itsdangerous token

Revision ID: 712cef586ede
Revises: 455b241372cf
Create Date: 2019-12-20 03:45:49.913488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712cef586ede'
down_revision = '455b241372cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
