"""empty message

Revision ID: a8bf44d3479a
Revises: ff99d7bbb0ea
Create Date: 2020-02-19 02:43:02.792042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bf44d3479a'
down_revision = 'ff99d7bbb0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_isbn', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('image', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('alternate_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('width', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('depth', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('translator', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('copyright_year', sa.DATETIME(), nullable=True),
    sa.Column('abstract', sa.TEXT(), nullable=True),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.Column('location_created', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('content_rating', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('date_published', sa.DATETIME(), nullable=True),
    sa.Column('in_language', sa.VARCHAR(length=100), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('review', sa.TEXT(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('translation_Work', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('work_translation', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('position', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('material', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('material_extent', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('title', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('title_english', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=100), nullable=True),
    sa.Column('illustrator', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('book_edition', sa.VARCHAR(length=100), nullable=True),
    sa.Column('book_format', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('number_pages', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('series', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('summary_html', sa.TEXT(), nullable=True),
    sa.Column('about_author', sa.TEXT(), nullable=True),
    sa.Column('about_author_html', sa.TEXT(), nullable=True),
    sa.Column('toc', sa.TEXT(), nullable=True),
    sa.Column('toc_html', sa.TEXT(), nullable=True),
    sa.Column('preface', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('discount_price', sa.INTEGER(), nullable=True),
    sa.Column('discount_rate', sa.FLOAT(), nullable=True),
    sa.Column('discount_date', sa.DATETIME(), nullable=True),
    sa.Column('paper_size', sa.VARCHAR(length=100), nullable=True),
    sa.Column('printing_color', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dimensions', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('number_category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('num_author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('keepsite', sa.VARCHAR(length=100), nullable=True),
    sa.Column('number_copies', sa.INTEGER(), nullable=True),
    sa.Column('bookmain_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bookmain_id'], ['bookmain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=1)
    # ### end Alembic commands ###
